Runs are not in proper order
samnissen/polariscope_2 pull request #98
Opened 2016-09-02 15:24 UTC by samnissen

Plus lots of Run UI improvements

2016-09-19 13:10 UTC, jhulme commented on app/models/run.rb
> +  before_save :do_not_update_completed_runs
This method has not been defined in the controller, or the relevant change is missing from this PR currently.

2016-09-19 13:10 UTC, jhulme requested changes

2016-09-27 08:25 UTC, samnissen commented on app/models/run.rb
> +  before_save :do_not_update_completed_runs
Change made -- please see commit

2016-09-29 16:07 UTC, jhulme commented
Yep all looks good now - runs fine.

2016-09-29 16:07 UTC, jhulme approved these changes

2016-10-07 16:23 UTC, merged